services:
  - type: web
    name: cookie-predictor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: girlscoutcookietracker-a26cf-firebase-adminsdk-ozpv8-a9f522f92b.json
    plan: free